import {
    Home, ShoppingCart, Car, Briefcase, Utensils, Plane, Book, Film,
    Gift, Heart, Music, Smartphone, Coffee, Dog, Shirt, Dumbbell,
    Scissors, Wifi, Droplet, Zap, Camera, Headphones, Monitor, Printer,
    Truck, CreditCard, DollarSign, Percent, TrendingUp,
    Umbrella, Wine, Feather, Framer, Cpu, HardDrive, Shield, PlayCircle,
    Sunset, Thermometer, Award, Tablet, Tv, Anchor, Bike, Box, Calendar,
    CloudRain, Compass, Disc, Gamepad, Globe, Key, Layers, Leaf, Map,
    MessageCircle, Moon, Palette, Paperclip, Pen, Save,
    Smile, Sun, Target, Trash, Users, Watch, Wind, Codesandbox
  } from 'lucide-react';
  
  export const iconOptions = [
    { name: 'Home', icon: Home },
    { name: 'Shopping', icon: ShoppingCart },
    { name: 'Car', icon: Car },
    { name: 'Work', icon: Briefcase },
    { name: 'Food', icon: Utensils },
    { name: 'Travel', icon: Plane },
    { name: 'Education', icon: Book },
    { name: 'Entertainment', icon: Film },
    { name: 'Gift', icon: Gift },
    { name: 'Health', icon: Heart },
    { name: 'Music', icon: Music },
    { name: 'Technology', icon: Smartphone },
    { name: 'Coffee', icon: Coffee },
    { name: 'Pets', icon: Dog },
    { name: 'Clothing', icon: Shirt },
    { name: 'Fitness', icon: Dumbbell },
    { name: 'Beauty', icon: Scissors },
    { name: 'Internet', icon: Wifi },
    { name: 'Water', icon: Droplet },
    { name: 'Electricity', icon: Zap },
    { name: 'Photography', icon: Camera },
    { name: 'Audio', icon: Headphones },
    { name: 'Computer', icon: Monitor },
    { name: 'Printing', icon: Printer },
    { name: 'Logistics', icon: Truck },
    { name: 'Credit Card', icon: CreditCard },
    { name: 'Finance', icon: DollarSign },
    { name: 'Discount', icon: Percent },
    { name: 'Investment', icon: TrendingUp },
    { name: 'Insurance', icon: Umbrella },
    { name: 'Wine', icon: Wine },
    { name: 'Writing', icon: Feather },
    { name: 'Design', icon: Framer },
    { name: 'Hardware', icon: Cpu },
    { name: 'Storage', icon: HardDrive },
    { name: 'Security', icon: Shield },
    { name: 'Media', icon: PlayCircle },
    { name: 'Weather', icon: Sunset },
    { name: 'Climate', icon: Thermometer },
    { name: 'Achievement', icon: Award },
    { name: 'Tablet', icon: Tablet },
    { name: 'Television', icon: Tv },
    { name: 'Marine', icon: Anchor },
    { name: 'Cycling', icon: Bike },
    { name: 'Package', icon: Box },
    { name: 'Calendar', icon: Calendar },
    { name: 'Weather', icon: CloudRain },
    { name: 'Navigation', icon: Compass },
    { name: 'Music', icon: Disc },
    { name: 'Gaming', icon: Gamepad },
    { name: 'Global', icon: Globe },
    { name: 'Security', icon: Key },
    { name: 'Layers', icon: Layers },
    { name: 'Nature', icon: Leaf },
    { name: 'Map', icon: Map },
    { name: 'Communication', icon: MessageCircle },
    { name: 'Night', icon: Moon },
    { name: 'Art', icon: Palette },
    { name: 'Attachment', icon: Paperclip },
    { name: 'Writing', icon: Pen },
    { name: 'Save', icon: Save },
    { name: 'Emotion', icon: Smile },
    { name: 'Weather', icon: Sun },
    { name: 'Target', icon: Target },
    { name: 'Trash', icon: Trash },
    { name: 'Users', icon: Users },
    { name: 'Time', icon: Watch },
    { name: 'Weather', icon: Wind },
    { name: 'Miscellaneous', icon: Codesandbox }
  ];
  
  export const getIconByName = (name) => {
    const iconOption = iconOptions.find(option => option.name.toLowerCase() === name.toLowerCase());
    return iconOption ? iconOption.icon : Codesandbox; // Default to Codesandbox if not found
  };